(******************************************************************)
(* DO NOT EDIT THIS FILE                                          *)
(******************************************************************)

open Jocalf

module type InterpSig = sig
  val interp_expr : string -> string
end

module InterpCheck : InterpSig = Interp

module type AuthorSig = sig
  val hours_worked : int
end

module AuthorCheck : AuthorSig = Author

let _ = if Author.hours_worked < 0 then exit 1
